version: '3'

services:
  db:
    container_name: postgres_database
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postpass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=taskmanagerdb
    volumes:
      - pg_data:/var/lib/postgres/data

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@al-software.com
      - PGADMIN_DEFAULT_PASSWORD=pgadpass
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050
    depends_on:
      - db

  backend:
    container_name: django_backend
    build:
      context: ../../backend
      dockerfile: django.Dockerfile
    restart: always
    environment:
      - DBNAME=taskmanagerdb
      - DBUSER=postgres
      - DBPASSWORD=postpass
      - DBHOST=db
      - DBPORT=5432
    command: >
      sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ../../backend:/usr/src/django-test-app/backend
    depends_on:
      - db

  frontend:
    container_name: react_frontend
    build:
      context: ../../frontend
      dockerfile: react.Dockerfile
    ports:
      - 3000:3000
    command: >
      sh -c "yarn start"
    volumes:
      - ../../frontend:/usr/src/django-test-app/frontend

volumes:
  pg_data:
